### ISSUE TITLE
cant find signed driver config in vc studio from instruction

### ISSUE THREAD

**Issue by Fjox** [vadimgrn/usbip-win2#97]

**Comment by vadimgrn** [comment]
Elaborate, pls

**Comment by Fjox** [comment]
> Elaborate, pls

baed on instruction i cant find where the setting is for the test certificate

**Comment by vadimgrn** [comment]
![Screenshot 2024-12-08 192736](https://github.com/user-attachments/assets/bc53dcbf-f9e4-4461-ad99-9c6cd48d41fd)

**Comment by Fjox** [comment]
fyi its not there

**Comment by eluna7** [comment]
also having this issue but i believe its because im on windows 10. the sdk and wdk do specifically say for windows 11. i believe like me, fjox may be on windows 10 and thats causing this issue. ~~un~~fortunately not gonna be installing win11, so i wont be able to compile this myself

saw another issue where the driver could potentially be signed but another third party so hoping that happens soonish:tm: !! ty for the work youve done on this vadmingrn <3

**Comment by Fjox** [comment]
im on windows 10 and im never gonan touch 11 again. that shit was ass
